CPMAddPackage(
  NAME JsonCpp
  GITLAB_REPOSITORY xvm/xvm-3rdparty/jsoncpp
  VERSION 1.9.5
  OPTIONS
    "JSONCPP_WITH_TESTS OFF"
    "JSONCPP_WITH_POST_BUILD_UNITTEST OFF"
    "JSONCPP_WITH_WARNING_AS_ERROR OFF"
    "JSONCPP_WITH_STRICT_ISO OFF"
    "JSONCPP_WITH_PKGCONFIG_SUPPORT OFF"
    "JSONCPP_WITH_CMAKE_PACKAGE OFF"
    "JSONCPP_WITH_EXAMPLE OFF"
    "JSONCPP_STATIC_WINDOWS_RUNTIME ON"
    "BUILD_SHARED_LIBS OFF"
    "BUILD_STATIC_LIBS ON"
    "BUILD_OBJECT_LIBS OFF"
)
